import { normalizeInterfaceLanguage } from '../i18n/language.js';


const DISPLAY_VALUE_RU = new Map(Object.entries({
  'Display name': 'Имя',
  'Headline': 'Заголовок',
  'Company': 'Компания',
  'City': 'Город',
  'Industry': 'Индустрия',
  'About': 'О себе',
  'Public LinkedIn URL': 'Публичная ссылка LinkedIn',
  'Hidden Telegram username': 'Скрытый Telegram username',
  'Search text': 'Поисковый запрос',
  'For you': 'Для вас',
  'AI & Tech': 'ИИ и технологии',
  'AI & Technology': 'ИИ и технологии',
  'Startups & Product': 'Стартапы и продукт',
  'Business & Markets': 'Бизнес и рынки',
  'Career & Leadership': 'Карьера и лидерство',
  'Crypto & Web3': 'Крипто и Web3',
  'Custom topic': 'Своя тема',
  'My professional network': 'Моя профессиональная сеть',
  'Founders & executives': 'Основатели и руководители',
  'Product & engineering': 'Продукт и разработка',
  'Sales & marketing': 'Продажи и маркетинг',
  'Investors & finance': 'Инвесторы и финансы',
  'Recruiters & talent': 'Рекрутеры и таланты',
  'Custom audience': 'Своя аудитория',
  'Expert take': 'Экспертный взгляд',
  'Practical lessons': 'Практические выводы',
  'Founder perspective': 'Взгляд основателя',
  'Explain simply': 'Объяснить просто',
  'Contrarian opinion': 'Альтернативное мнение',
  'Industry impact': 'Влияние на индустрию',
  'Career implications': 'Влияние на карьеру',
  'Professional': 'Профессиональный',
  'Analytical': 'Аналитический',
  'Concise': 'Краткий',
  'Founder': 'Основатель',
  'Growth': 'Рост',
  'Sales': 'Продажи',
  'Operations': 'Операции',
  'Product': 'Продукт',
  'Design': 'Дизайн',
  'Development': 'Разработка',
  'Marketing': 'Маркетинг',
  'Creator': 'Автор',
  'Recruiting': 'Рекрутинг',
  'B2B SaaS': 'B2B SaaS',
  'Crypto': 'Крипто',
  'Creator economy': 'Экономика авторов',
  'Agency / services': 'Агентство / услуги',
  'E-commerce': 'Электронная коммерция',
  'Recruiting / HR': 'Рекрутинг / HR',
  'Media': 'Медиа',
  'pending_recipient': 'ожидает решения получателя',
  'payment_pending': 'ожидает оплаты',
  'paid_pending_approval': 'оплачено, ожидает одобрения',
  'active': 'активен',
  'accepted': 'принят',
  'declined': 'отклонён',
  'revealed': 'контакт раскрыт',
  'cancelled': 'отменён',
  'expired': 'истёк',
  'unpaid': 'не оплачено',
  'paid': 'оплачено',
  'not charged': 'не списано',
  'available': 'доступно',
  'not available': 'недоступно',
  'not available yet': 'пока недоступно',
  'off': 'выключен',
  'earn_only': 'только начисление',
  'earn only': 'только начисление',
  'redeem': 'обмен доступен',
  'paused': 'приостановлен',
  'the invited member connected LinkedIn and reached listed-ready state': 'приглашённый участник подключил LinkedIn и достиг готовности к публикации'
}));

function translateDisplayValue(value) {
  const text = String(value ?? '');
  if (DISPLAY_VALUE_RU.has(text)) return DISPLAY_VALUE_RU.get(text);
  return text.split(' · ').map((part) => DISPLAY_VALUE_RU.get(part) || part).join(' · ');
}

const EXACT_LINE_RU = new Map(Object.entries({
  '⭐ Intro Deck Pro': '⭐ Intro Deck Pro',
  'Pro includes a bounded fair-use allowance for delivering private-chat and Telegram-contact requests.': 'Pro включает ограниченный суточный лимит на доставку запросов в приватный чат и запросов Telegram-контакта.',
  'Status: Not active': 'Статус: не активен',
  'Fair use': 'Лимиты использования',
  '• Payment covers request delivery. Recipient approval is always required.': '• Оплата покрывает доставку запроса. Решение всегда принимает получатель.',
  '• Acceptance or a reply is not guaranteed.': '• Принятие запроса или ответ не гарантируются.',
  '• A decline or no reply does not trigger an automatic refund for a delivered request.': '• Отказ или отсутствие ответа не запускают автоматический возврат за доставленный запрос.',
  'Story finder': 'Поиск инфоповодов',
  '• Every LinkedIn post still needs preview and separate approval.': '• Для каждой публикации LinkedIn по-прежнему нужны предпросмотр и отдельное подтверждение.',
  'Recent purchases': 'Недавние покупки',

  '⚙️ Optional profile details': '⚙️ Дополнительные данные профиля',
  'These fields improve your card or contact options, but they are not required to publish the profile.': 'Эти поля улучшают карточку и варианты связи, но не обязательны для публикации профиля.',
  'Optional profile editing is unavailable right now.': 'Редактирование дополнительных данных временно недоступно.',
  'Connect LinkedIn first before editing optional profile details.': 'Сначала подключите LinkedIn, затем редактируйте дополнительные данные.',
  'Hidden Telegram username stays private and is revealed only after an approved supported contact request.': 'Скрытый Telegram username остаётся приватным и раскрывается только после одобренного поддерживаемого контактного запроса.',
  '🧠 Skills selection': '🧠 Выбор навыков',
  'Pick the skills or lanes that best describe your work. At least 1 skill is required before the profile can become directory-ready.': 'Выберите направления, которые лучше всего описывают вашу работу. Для готовности профиля к каталогу нужен минимум 1 навык.',
  'Skill selection is temporarily unavailable. Try again later.': 'Выбор навыков временно недоступен. Попробуйте позже.',
  'Connect LinkedIn first before editing skills.': 'Сначала подключите LinkedIn, затем редактируйте навыки.',

  '🌐 Directory': '🌐 Каталог',
  'Browse published professional profiles. Private contact details stay hidden until approval.': 'Просматривайте опубликованные профессиональные профили. Приватные контакты скрыты до одобрения.',
  'No profiles match these filters.': 'По этим фильтрам профили не найдены.',
  'No profiles are listed yet. Complete your profile to join the directory.': 'В каталоге пока нет профилей. Завершите свой профиль, чтобы присоединиться.',
  'No profiles are listed yet. Your profile is ready to publish.': 'В каталоге пока нет профилей. Ваш профиль готов к публикации.',
  'No profiles are listed yet. Check back soon.': 'В каталоге пока нет профилей. Загляните позже.',
  '👤 Professional profile': '👤 Профессиональный профиль',
  'Listed profile not found.': 'Опубликованный профиль не найден.',
  'Private contact details stay hidden until the owner approves a supported request.': 'Приватные контакты скрыты, пока владелец не одобрит поддерживаемый запрос.',
  '🎯 Directory filters': '🎯 Фильтры каталога',
  'Use filters to narrow published profiles. Empty filters show the full directory.': 'Используйте фильтры, чтобы сузить список опубликованных профилей. Пустые фильтры показывают весь каталог.',
  'Directory filters are temporarily unavailable.': 'Фильтры каталога временно недоступны.',

  '📥 Requests': '📥 Запросы',
  'Choose which request inbox you want to open.': 'Выберите нужный раздел запросов.',
  '📥 Requests & chats': '📥 Запросы и чаты',
  'Your incoming and outgoing connection activity appears here.': 'Здесь отображаются входящие и исходящие запросы на связь.',
  'No intro requests yet.': 'Запросов на знакомство пока нет.',
  'No Telegram contact requests yet.': 'Запросов Telegram-контакта пока нет.',
  'No private chats yet.': 'Приватных чатов пока нет.',
  'Request details are temporarily unavailable.': 'Детали запроса временно недоступны.',
  'This request is no longer available.': 'Этот запрос больше недоступен.',
  'No contact details were shared.': 'Контактные данные не передавались.',
  'Your Telegram contact remains hidden.': 'Ваш Telegram-контакт остаётся скрытым.',

  '💬 Private chats': '💬 Приватные чаты',
  'Private chats open only after the recipient accepts a delivered permission request.': 'Приватный чат открывается только после того, как получатель примет доставленный запрос.',
  'Private chats are temporarily unavailable.': 'Приватные чаты временно недоступны.',
  'No private-chat requests or active chats yet.': 'Запросов в приватный чат и активных чатов пока нет.',
  'Chat details are temporarily unavailable.': 'Детали чата временно недоступны.',
  'This private chat is no longer available.': 'Этот приватный чат больше недоступен.',

  '✉️ Invite people': '✉️ Пригласить людей',
  'Invite professionals to join Intro Deck through your personal attributed link or Telegram card.': 'Приглашайте профессионалов в Intro Deck через персональную ссылку или Telegram-карточку.',
  'Your invite tools are temporarily unavailable.': 'Инструменты приглашений временно недоступны.',
  'No invited contacts yet.': 'Приглашённых контактов пока нет.',
  '📊 Invite activity': '📊 Активность приглашений',
  'This view shows joined and activated contacts attributed to your invite.': 'Здесь показаны присоединившиеся и активированные контакты по вашему приглашению.',
  'No invite activity yet.': 'Активности по приглашениям пока нет.',
  '📋 Invite history': '📋 История приглашений',
  'No invite history yet.': 'Истории приглашений пока нет.',
  '🎯 Points': '🎯 Баллы',
  'This screen shows your invite rewards status. Only available points can be spent.': 'Здесь показан статус наград за приглашения. Тратить можно только доступные баллы.',
  '<b>Your balance</b>': '<b>Ваш баланс</b>',
  '<b>How it works</b>': '<b>Как это работает</b>',
  '<b>Redeem status</b>': '<b>Статус обмена</b>',
  '<b>Recent reward events</b>': '<b>Недавние события наград</b>',
  '• Self-invites, existing users, and raw opens do not earn points.': '• Самоприглашения, существующие пользователи и простые открытия ссылок не начисляют баллы.',
  '• What changes by mode is shown below.': '• Ниже показано, что доступно в текущем режиме.',
  '• Redeem for Pro is live now. Spend from Available only.': '• Обмен на Pro доступен. Списываются только доступные баллы.',
  '• Earning is on and tracking is live. Redeem is not available yet.': '• Начисление и учёт включены. Обмен пока недоступен.',
  '• Rewards are paused right now. Existing balances stay visible, but no new actions go through.': '• Награды приостановлены. Балансы видны, новые действия не выполняются.',
  '• Rewards program is off right now. Existing balances stay visible, but no new actions go through.': '• Программа наград выключена. Балансы видны, новые действия не выполняются.',
  '• No reward events yet.': '• Событий наград пока нет.',
  '• Once a qualified invite confirms, it will appear here.': '• После подтверждения подходящего приглашения событие появится здесь.',
  '🔗 <b>Your invite link</b>': '🔗 <b>Ваша ссылка-приглашение</b>',
  'Copy this attributed link when you want to share outside the Telegram card flow.': 'Скопируйте эту персональную ссылку, чтобы поделиться вне Telegram-карточки.',

  '🗞 Story finder': '🗞 Поиск инфоповодов',
  'Find stories worth sharing with your professional network. Nothing is generated or published automatically.': 'Находите материалы, которыми стоит поделиться с профессиональной аудиторией. Ничего не создаётся и не публикуется автоматически.',
  'Find a source and create a reviewable LinkedIn draft. Nothing is published automatically.': 'Найдите источник и создайте проверяемый черновик для LinkedIn. Ничего не публикуется автоматически.',
  '🔎 Finding stories…': '🔎 Ищем инфоповоды…',
  'Checking official sources, releases, discussions, and news reports.': 'Проверяем официальные источники, релизы, обсуждения и новостные публикации.',
  'This message will update when the search finishes.': 'Это сообщение обновится после завершения поиска.',
  '⚠️ Search could not be completed': '⚠️ Не удалось завершить поиск',
  'Search allowance: restored.': 'Лимит поиска восстановлен.',
  'Search allowance: unchanged.': 'Лимит поиска не изменён.',
  'Search allowance: this completed attempt counts toward the rolling limit.': 'Эта завершённая попытка учитывается в скользящем лимите поиска.',
  'No draft or LinkedIn post was created.': 'Черновик и публикация LinkedIn не создавались.',
  '👥 LinkedIn audience': '👥 Аудитория LinkedIn',
  'Choose who should find the story professionally relevant. This guides discovery and draft framing; it does not target or message anyone.': 'Выберите, для кого материал должен быть профессионально полезен. Это влияет на поиск и подачу черновика, но никому не отправляет сообщения.',
  'Custom audience text is bounded to 120 characters and saved only in your preset settings.': 'Своя аудитория ограничена 120 символами и сохраняется только в настройках пресета.',
  '🎯 Editorial angle': '🎯 Редакционный ракурс',
  'Choose how the story should be framed for your audience.': 'Выберите, как подать материал вашей аудитории.',
  '✍️ Custom LinkedIn audience': '✍️ Своя аудитория LinkedIn',
  'Send a short description of the professional audience you want to reach.': 'Отправьте краткое описание профессиональной аудитории.',
  '✍️ Custom story topic': '✍️ Своя тема инфоповодов',
  'Send a short topic or query for source discovery.': 'Отправьте краткую тему или запрос для поиска источников.',
  '📝 Edit draft': '📝 Редактировать черновик',
  'Send the complete replacement text for this LinkedIn draft.': 'Отправьте полный новый текст для этого черновика LinkedIn.',
  '⚙️ Saved searches': '⚙️ Сохранённые поиски',
  'No saved searches yet.': 'Сохранённых поисков пока нет.',

  'This feature is temporarily unavailable. Try again later.': 'Эта функция временно недоступна. Попробуйте позже.',
  'This action could not be completed. Try again later.': 'Не удалось выполнить действие. Попробуйте позже.'
}));


const EXTRA_LINE_RU = new Map(Object.entries({
  '✏️ Edit Search text': '✏️ Редактировать поисковый запрос',
  '✏️ Edit City': '✏️ Редактировать город',
  'Send a short text query for listed profiles. It matches display name, headline, company, industry, and about.': 'Отправьте короткий поисковый запрос. Он проверяет имя, заголовок, компанию, индустрию и описание опубликованных профилей.',
  'Send a city or location fragment to narrow listed profiles.': 'Отправьте город или часть названия локации, чтобы сузить список профилей.',
  'Reply with plain text in the chat. Your next text message will update this directory filter.': 'Ответьте обычным текстом. Следующее сообщение обновит этот фильтр каталога.',
  'Reply with plain text in the chat. Your next text message will update this field.': 'Ответьте обычным текстом. Следующее сообщение обновит это поле.',
  'Use the buttons below to go back or return home.': 'Используйте кнопки ниже, чтобы вернуться назад или на главную.',
  'About': 'О себе',
  '🤝 Request contact': '🤝 Запросить связь',
  'Contact options are unavailable right now.': 'Варианты связи сейчас недоступны.',
  'This contact flow is not available for this profile.': 'Для этого профиля такой способ связи недоступен.',
  'Connect LinkedIn before sending contact requests.': 'Подключите LinkedIn перед отправкой контактных запросов.',
  'Your professional profile data remains member-provided.': 'Профессиональные данные профиля по-прежнему указываются участником.',
  'Every option goes to the profile owner and requires approval.': 'Каждый запрос отправляется владельцу профиля и требует его одобрения.',
  'Free intro request': 'Бесплатный запрос на знакомство',
  '• Sends a permission request directly to the profile owner.': '• Отправляет запрос на согласие непосредственно владельцу профиля.',
  '• Does not reveal a Telegram username or open a private chat.': '• Не раскрывает Telegram username и не открывает приватный чат.',
  '• Approval is not guaranteed.': '• Одобрение не гарантируется.',
  '• Send a first message with the request.': '• Добавьте первое сообщение к запросу.',
  '• Chat becomes active only after approval.': '• Чат становится активным только после одобрения.',
  '• Ask the owner to reveal the hidden Telegram username.': '• Попросите владельца раскрыть скрытый Telegram username.',
  '• No private chat is opened inside Intro Deck.': '• Приватный чат внутри Intro Deck не открывается.',
  'Stars or Pro cover request delivery only. Approval, contact reveal, or reply is not guaranteed. Decline or no reply alone does not trigger an automatic refund.': 'Stars или Pro покрывают только доставку запроса. Одобрение, раскрытие контакта или ответ не гарантируются. Отказ или отсутствие ответа сами по себе не запускают автоматический возврат.',
  'This profile is not accepting new contact requests right now.': 'Этот профиль сейчас не принимает новые контактные запросы.',
  'Review contact requests and continue approved private conversations.': 'Просматривайте контактные запросы и продолжайте одобренные приватные диалоги.',
  'Contact requests': 'Контактные запросы',
  '• Intro requests': '• Запросы на знакомство',
  '• Telegram contact requests': '• Запросы Telegram-контакта',
  'Private chats': 'Приватные чаты',
  '• New chat requests': '• Новые запросы в чат',
  '• Active conversations': '• Активные диалоги',
  '📨 Contact requests': '📨 Контактные запросы',
  'Review free intro requests and Telegram-contact requests.': 'Просматривайте бесплатные запросы на знакомство и запросы Telegram-контакта.',
  'Review private-chat requests and continue approved conversations.': 'Просматривайте запросы в приватный чат и продолжайте одобренные диалоги.',
  'Private chats are unavailable right now.': 'Приватные чаты сейчас недоступны.',
  'Incoming chat requests / threads:': 'Входящие запросы и диалоги:',
  'Sent chat requests / threads:': 'Исходящие запросы и диалоги:',
  'No private-chat requests yet. Open a listed profile and use Request contact.': 'Запросов в приватный чат пока нет. Откройте профиль в каталоге и выберите вариант связи.',
  '🧾 Private chat': '🧾 Приватный чат',
  'Review whether to open a private conversation with this member.': 'Проверьте запрос и решите, открывать ли приватный диалог с этим участником.',
  'Private chat detail is unavailable right now.': 'Детали приватного чата сейчас недоступны.',
  'Private chat not found.': 'Приватный чат не найден.',
  'Conversation:': 'Диалог:',
  'Use text, city, one industry bucket, and any number of skills to narrow listed profiles. Skill filters match any selected skill.': 'Используйте текст, город, одну категорию индустрии и любое число навыков, чтобы сузить каталог. Фильтр навыков совпадает по любому выбранному навыку.',
  'Directory filters are temporarily unavailable. Try again later.': 'Фильтры каталога временно недоступны. Попробуйте позже.',
  '💬 Private-chat request to this member': '💬 Запрос в приватный чат этому участнику',
  'Reply with the first message now.': 'Отправьте первое сообщение сейчас.',
  'The conversation opens only if the recipient accepts.': 'Диалог откроется только после согласия получателя.',
  'After you send the message, you can pay to deliver this permission request.': 'После сохранения сообщения можно оплатить доставку запроса на согласие.',
  'Send your next text message in chat now.': 'Отправьте следующее текстовое сообщение.',
  'It will be delivered inside this active private chat.': 'Оно будет доставлено внутри активного приватного чата.',
  '📝 Building an evidence-bound draft with the configured generator. Nothing will be published…': '📝 Создаём черновик на основе подтверждённого источника. Ничего не будет опубликовано…',
  '🧠 Running this preset now. It will create a draft only…': '🧠 Запускаем сохранённый поиск. Будет создан только черновик…',
  'Search is already in progress.': 'Поиск уже выполняется.',
  'Search started.': 'Поиск запущен.',
  'Topic preset updated.': 'Тема поиска обновлена.',
  'LinkedIn audience updated.': 'Аудитория LinkedIn обновлена.',
  'Editorial angle updated.': 'Редакционный ракурс обновлён.',
  'Post language updated.': 'Язык публикации обновлён.',
  'Tone updated.': 'Тон обновлён.',
  'Draft cancelled.': 'Черновик отменён.',
  'Current topic, audience, angle, language, and tone saved as a preset.': 'Текущие тема, аудитория, ракурс, язык и тон сохранены как пресет.',
  'Draft created from this saved preset. Nothing was published.': 'Черновик создан из сохранённого пресета. Ничего не опубликовано.',
  'Delivery schedule updated. Draft delivery never publishes automatically.': 'Расписание доставки обновлено. Доставка черновика никогда не публикует его автоматически.',
  'UTC delivery hour updated.': 'Час доставки по UTC обновлён.',
  'Preset paused.': 'Пресет приостановлен.',
  'Preset resumed.': 'Пресет возобновлён.',
  'Preset deleted.': 'Пресет удалён.',
  'Skills cleared.': 'Навыки очищены.',
  'Skill updated.': 'Навык обновлён.',
  'Contact mode updated.': 'Режим связи обновлён.',
  'Profile publication updated.': 'Публикация профиля обновлена.',
  'Profile visibility updated.': 'Видимость профиля обновлена.',
  'Filter cleared.': 'Фильтр очищен.',
  'Industry filter updated.': 'Фильтр индустрии обновлён.',
  'Skill filter updated.': 'Фильтр навыков обновлён.',
  'Filters cleared.': 'Фильтры очищены.',
  'Telegram contact request updated.': 'Запрос Telegram-контакта обновлён.',
  'Private chat updated.': 'Приватный чат обновлён.',
  'Not enough available points yet.': 'Пока недостаточно доступных баллов.',
  'Not enough available points.': 'Недостаточно доступных баллов.',
  'This reward item is not available.': 'Эта награда недоступна.',
  'Redeem is not live yet. Earn-only mode keeps balances visible without spending.': 'Обмен пока недоступен. В режиме начисления балансы видны без возможности списания.',
  'Redeem is not live yet.': 'Обмен пока недоступен.',
  'Rewards are paused right now.': 'Награды сейчас приостановлены.',
  'Rewards program is off right now.': 'Программа наград сейчас выключена.',
  'Could not open redeem right now.': 'Не удалось открыть обмен.',
  'This reward redemption was already completed.': 'Этот обмен награды уже был завершён.',
  'This redeem confirmation is no longer available.': 'Это подтверждение обмена больше недоступно.',
  'Could not complete this redeem right now.': 'Не удалось завершить обмен.',
  'See invite totals, attribution sources, recent movement, and the latest joined contacts.': 'Просматривайте общие показатели, источники атрибуции, недавнюю динамику и последних присоединившихся контактов.',
  '<b>All-time</b>': '<b>За всё время</b>',
  '<b>By source</b>': '<b>По источникам</b>',
  '<b>Last 7 days</b>': '<b>Последние 7 дней</b>',
  '<b>Activation rule</b>': '<b>Правило активации</b>',
  '<b>Recent activity</b>': '<b>Недавняя активность</b>',
  '<b>Summary</b>': '<b>Сводка</b>',
  '<b>History window</b>': '<b>Диапазон истории</b>',
  '<b>Contacts</b>': '<b>Контакты</b>',
  'Everyone who joined from your invite appears here.': 'Здесь отображаются все, кто присоединился по вашему приглашению.',
  '• No invite activity yet.': '• Активности по приглашениям пока нет.',
  '• Share your card or attributed link to start tracking activity.': '• Поделитесь карточкой или персональной ссылкой, чтобы начать отслеживание.',
  '• No invited contacts yet.': '• Приглашённых контактов пока нет.',
  '• Your first joined contact will appear here automatically.': '• Первый присоединившийся контакт появится здесь автоматически.',
  'Choose the professional lens for source ranking and draft framing. Facts remain bounded to the original evidence.': 'Выберите профессиональный ракурс для ранжирования источников и подачи черновика. Факты остаются ограничены исходными доказательствами.',

  '• Active Pro includes up to 10 combined contact-request deliveries per rolling 24 hours across private-chat and Telegram-contact options, subject to recipient cooldowns and abuse controls.': '• Активный Pro включает до 10 доставок контактных запросов за скользящие 24 часа для приватного чата и Telegram-контакта с учётом пауз получателя и защиты от злоупотреблений.',
  'Public LinkedIn URL: shared after accepted intro': 'Публичная ссылка LinkedIn: открывается после принятого запроса',
  'Public LinkedIn URL: not provided': 'Публичная ссылка LinkedIn: не указана',
  'Contact: private chat or Telegram contact • recipient approval required': 'Связь: приватный чат или Telegram-контакт • требуется одобрение получателя',
  'Share your personal Intro Deck invite. Activity and rewards are tracked automatically.': 'Поделитесь персональным приглашением в Intro Deck. Активность и награды учитываются автоматически.',
  'Share your personal Intro Deck invite into any chat': 'Отправьте персональное приглашение Intro Deck в любой чат',
  'Send the display name for your directory card.': 'Отправьте имя для карточки в каталоге.',
  'Send a short professional headline.': 'Отправьте короткий профессиональный заголовок.',
  'Send your current company or project name.': 'Отправьте название текущей компании или проекта.',
  'Send your city or primary location.': 'Отправьте город или основную локацию.',
  'Send your industry or main category.': 'Отправьте индустрию или основную категорию.',
  'Send a short about section for your directory card.': 'Отправьте короткое описание для карточки в каталоге.',
  'Send your public LinkedIn profile URL. Example: https://www.linkedin.com/in/your-name': 'Отправьте публичную ссылку на профиль LinkedIn. Пример: https://www.linkedin.com/in/your-name',
  'Send your Telegram username without @ or t.me/. This stays hidden and can only be revealed after an approved Telegram contact request.': 'Отправьте Telegram username без @ и t.me/. Он останется скрытым и будет раскрыт только после одобренного запроса Telegram-контакта.',
}));

const EXACT_BUTTON_RU = new Map(Object.entries({
  '🏠 Home': '🏠 Главная',
  '← Back to profile': '← Назад к профилю',
  '← Back to directory': '← Назад в каталог',
  '← Back to requests': '← Назад к запросам',
  '↩️ Back to filters': '↩️ Назад к фильтрам',
  '🌐 Browse directory': '🌐 Открыть каталог',
  '🎯 Filters': '🎯 Фильтры',
  '🧹 Clear filters': '🧹 Очистить фильтры',
  '🧹 Clear skills': '🧹 Очистить навыки',
  '➡️ Continue setup': '➡️ Продолжить настройку',
  '👁 Review listed profile': '👁 Проверить опубликованный профиль',
  '👁 Preview & publish': '👁 Проверить и опубликовать',
  '⚙️ Optional details & contact': '⚙️ Дополнительные данные и контакты',
  '🏢 Company': '🏢 Компания',
  '📍 City': '📍 Город',
  '🔗 LinkedIn URL': '🔗 Ссылка LinkedIn',
  '🔐 Telegram': '🔐 Telegram',
  '💳 Contact mode': '💳 Режим связи',
  '👁 Preview card': '👁 Предпросмотр карточки',
  '‹ Previous': '‹ Назад',
  'Next ›': 'Далее ›',
  '📥 Intro requests': '📥 Запросы на знакомство',
  '🔐 Telegram requests': '🔐 Запросы Telegram-контакта',
  '💬 Private chats': '💬 Приватные чаты',
  '✅ Accept': '✅ Принять',
  '❌ Decline': '❌ Отклонить',
  '🚫 Block': '🚫 Заблокировать',
  '⚠️ Report': '⚠️ Пожаловаться',
  '💬 Reply': '💬 Ответить',
  '📨 Invite people': '📨 Пригласить людей',
  '📊 Activity': '📊 Активность',
  '📋 Full history': '📋 Полная история',
  '🎯 Points': '🎯 Баллы',
  '🔗 Show invite link': '🔗 Показать ссылку',
  '📤 Send forwarding card': '📤 Отправить карточку',
  '↩️ Invite people': '↩️ К приглашениям',
  '✨ Redeem for Pro': '✨ Обменять на Pro',
  '🔒 Redeem for Pro': '🔒 Обмен на Pro',
  '⏸️ Redeem paused': '⏸️ Обмен приостановлен',
  '🚫 Redeem off': '🚫 Обмен выключен',
  '🔎 Find stories': '🔎 Найти инфоповоды',
  '📝 Open current draft': '📝 Открыть текущий черновик',
  '➕ Save search': '➕ Сохранить поиск',
  '⭐ Get Pro': '⭐ Подключить Pro',
  '⏳ Search in progress': '⏳ Поиск выполняется',
  '🔄 Try again': '🔄 Повторить',
  '← News settings': '← Настройки инфоповодов',
  '← Back to story finder': '← Назад к поиску инфоповодов',
  'Cancel': 'Отмена',
  'Cancel edit': 'Отменить редактирование',

  '🌐 Browse': '🌐 Каталог',
  '✏️ Display name': '✏️ Имя',
  '✏️ Headline': '✏️ Заголовок',
  '✏️ Industry': '✏️ Индустрия',
  '✏️ About': '✏️ О себе',
  '✨ For you': '✨ Для вас',
  '🤖 AI & Tech': '🤖 ИИ и технологии',
  '🚀 Startups': '🚀 Стартапы',
  '📈 Business': '📈 Бизнес',
  '🧭 Career': '🧭 Карьера',
  '🪙 Crypto': '🪙 Крипто',
  '⛓ Crypto': '⛓ Крипто',
  '✍️ Custom': '✍️ Своя тема',
  'My professional network': 'Моя профессиональная сеть',
  'Founders & executives': 'Основатели и руководители',
  'Product & engineering': 'Продукт и разработка',
  'Sales & marketing': 'Продажи и маркетинг',
  'Investors & finance': 'Инвесторы и финансы',
  'Recruiters & talent': 'Рекрутеры и таланты',
  'Custom audience': 'Своя аудитория',
  'Expert take': 'Экспертный взгляд',
  'Practical lessons': 'Практические выводы',
  'Founder perspective': 'Взгляд основателя',
  'Explain simply': 'Объяснить просто',
  'Contrarian opinion': 'Альтернативное мнение',
  'Industry impact': 'Влияние на индустрию',
  'Career implications': 'Влияние на карьеру',
}));


const EXTRA_BUTTON_RU = new Map(Object.entries({
  '🌐 Publish my profile': '🌐 Опубликовать мой профиль',
  '👁 Preview my profile': '👁 Предпросмотр моего профиля',
  '🔗 Open my LinkedIn': '🔗 Открыть мой LinkedIn',
  '🔗 Open LinkedIn': '🔗 Открыть LinkedIn',
  '🤝 Contact options': '🤝 Варианты связи',
  '🔗 Connect LinkedIn': '🔗 Подключить LinkedIn',
  '✉️ Send free intro request': '✉️ Отправить бесплатный запрос',
  '📥 Contact requests': '📥 Контактные запросы',
  '↩️ Back to inbox': '↩️ Назад к входящим',
  '👤 Open profile': '👤 Открыть профиль',
  '✉️ Send message': '✉️ Отправить сообщение',
  '↩️ Back to Private chats': '↩️ Назад к приватным чатам',
  '✖️ Clear search': '✖️ Очистить поиск',
  '✖️ Clear city': '✖️ Очистить город',
  '✅ Confirm': '✅ Подтвердить',
  '↩️ Back to redeem': '↩️ Назад к обмену',
  '⬅️ Prev': '⬅️ Назад',
  'Next ➡️': 'Далее ➡️',
  '📨 Share to a chat': '📨 Отправить в чат',
  '🔗 Copy invite link': '🔗 Скопировать ссылку'
}));

const MESSAGE_RU = Object.freeze({
  temporarilyUnavailable: '⚠️ Эта функция временно недоступна. Попробуйте позже.',
  profileSetupConnectLinkedIn: 'Сначала подключите LinkedIn, чтобы продолжить настройку профиля.',
  couldNotContinueProfile: 'Не удалось продолжить настройку профиля.',
  skillsCleared: '✅ Навыки очищены. Выберите минимум 1 навык для завершения обязательной настройки.',
  skillAdded: ({ label = 'навык' }) => `✅ Добавлен навык: ${label}`,
  skillRemoved: ({ label = 'навык' }) => `✅ Удалён навык: ${label}`,
  directoryFiltersCleared: '✅ Фильтры каталога очищены.',
  introInboxUpdated: 'Входящие запросы обновлены.',
  requestSent: ({ name = 'этого профиля' }) => `✅ Запрос на знакомство сохранён для ${name}.`,
  recipientNotified: ' Получатель получил уведомление в Telegram.',
  recipientAlreadyRecorded: ' Уведомление получателя уже было зафиксировано.',
  recipientNoticeSkipped: ' Уведомление получателю пропущено.',
  recipientNoticeFailed: ' Не удалось доставить уведомление, но запрос сохранён.',
  postLanguageUpdated: '✅ Язык публикации обновлён.',
  topicPresetUpdated: '✅ Тема поиска обновлена.',
  audienceUpdated: '✅ Аудитория LinkedIn обновлена.',
  angleUpdated: '✅ Редакционный ракурс обновлён.',
  toneUpdated: '✅ Тон обновлён.',
  searchAlreadyRunning: 'Поиск уже выполняется.',
  searchStarted: 'Поиск запущен.',
  forwardingCardSent: 'Карточка для пересылки отправлена ниже.'
});

function replaceDynamicLine(line) {
  const rules = [
    [/^Search: (.*)$/u, (_, value) => `Поиск: ${value}`],
    [/^✅ Redeemed: (.*) applied\.$/u, (_, value) => `✅ Обмен завершён: ${value}.`],
    [/^✅ Added skill: (.*)$/u, (_, value) => `✅ Добавлен навык: ${translateDisplayValue(value)}`],
    [/^✅ Removed skill: (.*)$/u, (_, value) => `✅ Удалён навык: ${translateDisplayValue(value)}`],
    [/^✅ Industry filter: (.*)$/u, (_, value) => `✅ Фильтр индустрии: ${translateDisplayValue(value)}`],
    [/^✅ Skill filter: (.*)$/u, (_, value) => `✅ Фильтр навыков: ${translateDisplayValue(value)}`],
    [/^• Activation rate: (.*)$/u, (_, value) => `• Доля активаций: ${value}`],
    [/^• Share to a chat: (.*)$/u, (_, value) => `• Отправка в чат: ${value}`],
    [/^• Copy invite link: (.*)$/u, (_, value) => `• Копирование ссылки: ${value}`],
    [/^• Forwarding card: (.*)$/u, (_, value) => `• Карточка для пересылки: ${value}`],
    [/^• Current signal: (.*)\.$/u, (_, value) => `• Текущий сигнал: ${translateDisplayValue(value)}.`],
    [/^• Showing: (.*)$/u, (_, value) => `• Показано: ${value}`],
    [/^• Page: (.*)$/u, (_, value) => `• Страница: ${value}`],
    [/^Public LinkedIn URL: (https?:\/\/.*)$/u, (_, value) => `Публичная ссылка LinkedIn: ${value}`],
    [/^Received: (\d+)\/(\d+) pending\/total$/u, (_, pending, total) => `Входящие: ${pending}/${total} ожидают/всего`],
    [/^Sent: (\d+)\/(\d+) pending\/total$/u, (_, pending, total) => `Исходящие: ${pending}/${total} ожидают/всего`],
    [/^Received chat requests: (\d+)\/(\d+) pending\/total$/u, (_, pending, total) => `Входящие запросы в чат: ${pending}/${total} ожидают/всего`],
    [/^Sent chat requests: (\d+)\/(\d+) pending\/total$/u, (_, pending, total) => `Исходящие запросы в чат: ${pending}/${total} ожидают/всего`],
    [/^Invited: (.*)$/u, (_, value) => `Приглашено: ${value}`],
    [/^Activated: (.*)$/u, (_, value) => `Активировано: ${value}`],
    [/^• Invited: (.*)$/u, (_, value) => `• Приглашено: ${value}`],
    [/^• Activated: (.*)$/u, (_, value) => `• Активировано: ${value}`],
    [/^✏️ Edit (Display name|Headline|Company|City|Industry|About|Public LinkedIn URL|Hidden Telegram username)$/u, (_, value) => `✏️ Редактировать: ${translateDisplayValue(value)}`],
    [/^Status: Active until (.+)$/u, (_, value) => `Статус: активен до ${value}`],
    [/^Status: Inactive · expired (.+)$/u, (_, value) => `Статус: неактивен · истёк ${value}`],
    [/^(\d+)⭐ for (\d+) days$/u, (_, price, days) => `${price}⭐ на ${days} дней`],
    [/^Telegram contact request: (\d+)⭐ without Pro$/u, (_, price) => `Запрос Telegram-контакта: ${price}⭐ без Pro`],
    [/^Private chat request: (\d+)⭐ without Pro$/u, (_, price) => `Запрос в приватный чат: ${price}⭐ без Pro`],
    [/^• Current window: (\d+)\/(\d+) used · (\d+) left$/u, (_, used, limit, left) => `• Текущее окно: использовано ${used}/${limit} · осталось ${left}`],
    [/^• (\d+) draft attempts per rolling 24 hours\.$/u, (_, count) => `• ${count} попыток создать черновик за скользящие 24 часа.`],
    [/^• (\d+) saved searches\.$/u, (_, count) => `• Сохранённых поисков: ${count}.`],
    [/^Selected skills: (.*)$/u, (_, value) => `Выбранные навыки: ${value}`],
    [/^Profile completion: (.*)$/u, (_, value) => `Заполнение профиля: ${value}`],
    [/^Directory readiness: (.*)$/u, (_, value) => `Готовность к каталогу: ${value}`],
    [/^Contact mode: (.*)$/u, (_, value) => `Режим связи: ${value}`],
    [/^Profiles: (\d+) · Page (\d+)$/u, (_, count, page) => `Профилей: ${count} · Страница ${page}`],
    [/^Page (\d+) of (\d+)$/u, (_, page, pages) => `Страница ${page} из ${pages}`],
    [/^Topic: (.*)$/u, (_, value) => `Тема: ${translateDisplayValue(value)}`],
    [/^Audience: (.*)$/u, (_, value) => `Аудитория: ${translateDisplayValue(value)}`],
    [/^Angle: (.*)$/u, (_, value) => `Ракурс: ${translateDisplayValue(value)}`],
    [/^Profile context: Off$/u, () => 'Контекст профиля: выключен'],
    [/^Profile context: On$/u, () => 'Контекст профиля: включён'],
    [/^Profile context: On · complete your profile for better matches$/u, () => 'Контекст профиля: включён · заполните профиль для более точного подбора'],
    [/^Post language: (.*)$/u, (_, value) => `Язык публикации: ${translateDisplayValue(value)}`],
    [/^Tone: (.*)$/u, (_, value) => `Тон: ${translateDisplayValue(value)}`],
    [/^Searches: (.*)$/u, (_, value) => `Поиски: ${value}`],
    [/^Searches left: (.*)$/u, (_, value) => `Осталось поисков: ${value}`],
    [/^Saved searches: (.*)$/u, (_, value) => `Сохранённые поиски: ${value}`],
    [/^Available again: (.*)$/u, (_, value) => `Снова доступно: ${value}`],
    [/^Selected: (.*)$/u, (_, value) => `Выбрано: ${translateDisplayValue(value)}`],
    [/^Current value: (.*)$/u, (_, value) => `Текущее значение: ${translateDisplayValue(value)}`],
    [/^• Current value: (.*)$/u, (_, value) => `• Текущее значение: ${translateDisplayValue(value)}`],
    [/^Limit: (\d+) characters$/u, (_, value) => `Лимит: ${value} символов`],
    [/^• Limit: (\d+) characters$/u, (_, value) => `• Лимит: ${value} символов`],
    [/^Pending: (.*)$/u, (_, value) => `Ожидает: ${value}`],
    [/^Available: (.*)$/u, (_, value) => `Доступно: ${value}`],
    [/^Redeemed: (.*)$/u, (_, value) => `Использовано: ${value}`],
    [/^• Pending: (.*)$/u, (_, value) => `• Ожидает: ${value}`],
    [/^• Available: (.*)$/u, (_, value) => `• Доступно: ${value}`],
    [/^• Redeemed: (.*)$/u, (_, value) => `• Использовано: ${value}`],
    [/^• Mode: (.*)$/u, (_, value) => `• Режим: ${translateDisplayValue(value)}`],
    [/^• Activation signal: (.*?)\.?$/u, (_, value) => `• Сигнал активации: ${translateDisplayValue(value)}.`],
    [/^• Pending confirms after (\d+)h if the activation still holds\.$/u, (_, hours) => `• Ожидающие баллы подтверждаются через ${hours} ч, если активация сохраняется.`],
    [/^Company: (.*)$/u, (_, value) => `Компания: ${value}`],
    [/^City: (.*)$/u, (_, value) => `Город: ${value}`],
    [/^Industry: (.*)$/u, (_, value) => `Индустрия: ${value}`],
    [/^Skills: (.*)$/u, (_, value) => `Навыки: ${value}`],
    [/^Received chat requests: (.*)$/u, (_, value) => `Входящие запросы в чат: ${value}`],
    [/^Sent chat requests: (.*)$/u, (_, value) => `Исходящие запросы в чат: ${value}`],
    [/^Active conversations: (.*)$/u, (_, value) => `Активные диалоги: ${value}`],
    [/^Perspective: Received private-chat request$/u, () => 'Роль: полученный запрос в приватный чат'],
    [/^Perspective: Sent private-chat request$/u, () => 'Роль: отправленный запрос в приватный чат'],
    [/^Member: (.*)$/u, (_, value) => `Участник: ${value}`],
    [/^Headline: (.*)$/u, (_, value) => `Заголовок: ${value}`],
    [/^Status: (.*)$/u, (_, value) => `Статус: ${translateDisplayValue(value)}`],
    [/^Delivery coverage: Pro fair-use allowance$/u, () => 'Доставка: лимит Pro'],
    [/^Payment: (.*)$/u, (_, value) => `Оплата: ${translateDisplayValue(value)}`],
    [/^Reference per-request price: (.*)$/u, (_, value) => `Справочная цена запроса: ${value}`],
    [/^Request-delivery fee: (.*)$/u, (_, value) => `Стоимость доставки запроса: ${value}`],
    [/^Created: (.*)$/u, (_, value) => `Создано: ${value}`],
    [/^First message: (.*)$/u, (_, value) => `Первое сообщение: ${value}`],
    [/^Private chat • (.*)$/u, (_, value) => `Приватный чат • ${value}`],
    [/^Telegram contact • (.*)$/u, (_, value) => `Telegram-контакт • ${value}`],
    [/^Search will be ready in (\d+)s\.$/u, (_, value) => `Поиск будет доступен через ${value} с.`],
    [/^Search cooldown: try again in (\d+)s\.$/u, (_, value) => `Пауза поиска: повторите через ${value} с.`],
    [/^✏️ Edit (.*)$/u, (_, value) => `✏️ Редактировать: ${value}`],
    [/^💬 Private-chat request to (.*)$/u, (_, value) => `💬 Запрос в приватный чат: ${value}`],
    [/^💬 Reply to (.*)$/u, (_, value) => `💬 Ответ для ${value}`],
    [/^✅ Topic preset updated\.$/u, () => '✅ Тема поиска обновлена.'],
    [/^✅ LinkedIn audience updated\.$/u, () => '✅ Аудитория LinkedIn обновлена.'],
    [/^✅ Editorial angle updated\.$/u, () => '✅ Редакционный ракурс обновлён.'],
    [/^✅ Post language updated\.$/u, () => '✅ Язык публикации обновлён.'],
    [/^✅ Tone updated\.$/u, () => '✅ Тон обновлён.']
  ];
  for (const [pattern, formatter] of rules) {
    if (pattern.test(line)) return line.replace(pattern, formatter);
  }
  return line;
}

function translateLine(line) {
  if (EXACT_LINE_RU.has(line)) return EXACT_LINE_RU.get(line);
  if (EXTRA_LINE_RU.has(line)) return EXTRA_LINE_RU.get(line);
  return replaceDynamicLine(line);
}

function translateButton(text) {
  if (EXACT_BUTTON_RU.has(text)) return EXACT_BUTTON_RU.get(text);
  if (EXTRA_BUTTON_RU.has(text)) return EXTRA_BUTTON_RU.get(text);
  const rules = [
    [/^(✓ )?(✨ For you|🤖 AI & Tech|🚀 Startups|📈 Business|🧭 Career|(?:🪙|⛓) Crypto|✍️ Custom)$/u, (_, selected, value) => `${selected || ''}${EXACT_BUTTON_RU.get(value) || value}`],
    [/^(✓ )?(My professional network|Founders & executives|Product & engineering|Sales & marketing|Investors & finance|Recruiters & talent|Custom audience)$/u, (_, selected, value) => `${selected || ''}${translateDisplayValue(value)}`],
    [/^(👥|🎯) (.+)$/u, (_, icon, value) => `${icon} ${translateDisplayValue(value)}`],
    [/^(✓ )?(Expert take|Practical lessons|Founder perspective|Explain simply|Contrarian opinion|Industry impact|Career implications)$/u, (_, selected, value) => `${selected || ''}${translateDisplayValue(value)}`],
    [/^(✓ )?(Founder|Growth|Sales|Operations|Product|Design|Development|Marketing|Creator|Recruiting|B2B SaaS|Crypto)$/u, (_, selected, value) => `${selected || ''}${translateDisplayValue(value)}`],
    [/^(✓ )?(Creator economy|Agency \/ services|E-commerce|Recruiting \/ HR|Media)$/u, (_, selected, value) => `${selected || ''}${translateDisplayValue(value)}`],
    [/^⭐ Buy 30 days of Pro · (.+)$/u, (_, value) => `⭐ Купить 30 дней Pro · ${value}`],
    [/^✅ Pro active until (.+)$/u, (_, value) => `✅ Pro активен до ${value}`],
    [/^Language: (.+)$/u, (_, value) => `Язык: ${translateDisplayValue(value)}`],
    [/^Tone: (.+)$/u, (_, value) => `Тон: ${translateDisplayValue(value)}`],
    [/^⚙️ Saved searches \((\d+)\)$/u, (_, count) => `⚙️ Сохранённые поиски (${count})`],
    [/^📋 Full history \((\d+)\)$/u, (_, count) => `📋 Полная история (${count})`],
    [/^✅ (.+) · (\d+) pts$/u, (_, label, points) => `✅ ${label} · ${points} баллов`],
    [/^🔒 (.+) · (\d+) pts$/u, (_, label, points) => `🔒 ${label} · ${points} баллов`],
    [/^💬 Private chat • (.*)$/u, (_, value) => `💬 Приватный чат • ${value}`],
    [/^🔐 Telegram contact • (.*)$/u, (_, value) => `🔐 Telegram-контакт • ${value}`],
    [/^🔎 Search: (.*)$/u, (_, value) => `🔎 Поиск: ${value}`],
    [/^📍 City: (.*)$/u, (_, value) => `📍 Город: ${value}`]
  ];
  for (const [pattern, formatter] of rules) {
    if (pattern.test(text)) return text.replace(pattern, formatter);
  }
  return text;
}

export function localizeMemberText(text, interfaceLanguage = 'en') {
  if (normalizeInterfaceLanguage(interfaceLanguage) !== 'ru') return text;
  return String(text || '').split('\n').map(translateLine).join('\n');
}

export function localizeMemberKeyboard(replyMarkup, interfaceLanguage = 'en') {
  if (normalizeInterfaceLanguage(interfaceLanguage) !== 'ru' || !replyMarkup?.inline_keyboard) return replyMarkup;
  return {
    ...replyMarkup,
    inline_keyboard: replyMarkup.inline_keyboard.map((row) => row.map((button) => ({
      ...button,
      text: translateButton(String(button?.text || ''))
    })))
  };
}

export function localizeMemberSurface(surface, interfaceLanguage = 'en') {
  if (!surface || normalizeInterfaceLanguage(interfaceLanguage) !== 'ru') return surface;
  return {
    ...surface,
    text: localizeMemberText(surface.text, interfaceLanguage),
    reply_markup: localizeMemberKeyboard(surface.reply_markup, interfaceLanguage)
  };
}

export function memberMessage(key, interfaceLanguage = 'en', params = {}) {
  if (normalizeInterfaceLanguage(interfaceLanguage) !== 'ru') return null;
  const entry = MESSAGE_RU[key];
  return typeof entry === 'function' ? entry(params) : entry || null;
}
